# -*- coding: utf-8 -*-
"""230818 이미지 url 다운.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oAnry80hk_oM2SLkwDjIRmlKKT9lPY93
"""

!pip install pymysql

import urllib.request
import time
import pymysql

conn = pymysql.connect(host='blogdb.cm2yxwfja9ii.ap-northeast-2.rds.amazonaws.com',
                      user='admin',
                      password='blogdb!2',
                      database='Naver_Blogs',
                      port=3306)
curs=conn.cursor()

query="SELECT img_ID,img_url FROM blog_img_url where not img_url like '%post%' order by img_ID;"

curs.execute(query)

# Fetch all the rows
data = curs.fetchall()
#range(len(data))

img_folder = "/content/imgs/"

for i in data:
  try:
    url = i[1]
    urllib.request.urlretrieve(url, img_folder+str(i[0])+".jpg")
  except:
    print(i)

